blueprint:
  name: Reolink Rich Notifications
  description: >
    Send Reolink rich notifications to an Android device.

    Documentation: https://github.com/jterrace/ha-reolink-rich-notifications

  domain: automation
  input:
    notify_device:
      name: Devices to Notify
      description: These mobile devices will receive a notification when alerts are triggered.
      default: []
      selector:
        device:
          integration: mobile_app
          multiple: true

    camera_entity:
      name: Camera Entity
      description: Choose the Reolink camera to use for snapshots.
      selector:
        entity:
          domain: camera
          integration: reolink
          multiple: false

    retrigger_delay:
      name: Retrigger Delay
      description: Time to wait before triggering the same camera again.
      default:
        hours: 0
        minutes: 0
        seconds: 20
      selector:
        duration:

mode: parallel
max: 100

variables:
  notify_device: !input notify_device
  camera_entity: !input camera_entity
  retrigger_delay: !input retrigger_delay
  image_file: "reolink_rich_notifications/{{ camera_entity }}_{{ now().timestamp() | int }}.jpg"

trigger:
  platform: state
  entity_id: !input camera_entity
  from: "off"
  to: "on"

action:
  # Send notification without image
  - repeat:
      for_each: "{{ notify_device }}"
      sequence:
        - service: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}"
          data:
            title: "{{ trigger.from_state.attributes.friendly_name }}"
            message: ""
            data:
              tag: "{{ trigger.to_state.context.id }}"
              ttl: 0
              priority: high
              url: "app://com.mcu.reolink"
              clickAction: "app://com.mcu.reolink"

  # Create camera snapshot
  - service: camera.snapshot
    data:
      entity_id: "{{ camera_entity }}"
      filename: "/media/{{ image_file }}"

  # Re-send notification with image data
  - repeat:
      for_each: "{{ notify_device }}"
      sequence:
        - service: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}"
          data:
            title: "{{ trigger.from_state.attributes.friendly_name }}"
            message: ""
            data:
              tag: "{{ trigger.to_state.context.id }}"
              image: "/media/local/{{ image_file }}"
              ttl: 0
              priority: high
              url: "app://com.mcu.reolink"
              clickAction: "app://com.mcu.reolink"
